// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbSl5tC_T7cQWRywjnYVpbuOD2lOGGzs0',
    appId: '1:33187235126:web:143a436a8ed5f999811f97',
    messagingSenderId: '33187235126',
    projectId: 'airplane-management-1ce20',
    authDomain: 'airplane-management-1ce20.firebaseapp.com',
    storageBucket: 'airplane-management-1ce20.firebasestorage.app',
    measurementId: 'G-PWFWDJL0XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjtygUyY8sraEaTP924GmBRlZYlRfrak',
    appId: '1:33187235126:android:679d47e5bfeb520e811f97',
    messagingSenderId: '33187235126',
    projectId: 'airplane-management-1ce20',
    storageBucket: 'airplane-management-1ce20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYA00G_aPJYDfpdMwTWVpQ7SBvK27WZc4',
    appId: '1:33187235126:ios:857ec666ac27f068811f97',
    messagingSenderId: '33187235126',
    projectId: 'airplane-management-1ce20',
    storageBucket: 'airplane-management-1ce20.firebasestorage.app',
    iosBundleId: 'com.example.airplaneManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYA00G_aPJYDfpdMwTWVpQ7SBvK27WZc4',
    appId: '1:33187235126:ios:857ec666ac27f068811f97',
    messagingSenderId: '33187235126',
    projectId: 'airplane-management-1ce20',
    storageBucket: 'airplane-management-1ce20.firebasestorage.app',
    iosBundleId: 'com.example.airplaneManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbSl5tC_T7cQWRywjnYVpbuOD2lOGGzs0',
    appId: '1:33187235126:web:881f964a92e03569811f97',
    messagingSenderId: '33187235126',
    projectId: 'airplane-management-1ce20',
    authDomain: 'airplane-management-1ce20.firebaseapp.com',
    storageBucket: 'airplane-management-1ce20.firebasestorage.app',
    measurementId: 'G-QE9GV1RD56',
  );
}
